# -*- coding: utf-8 -*-
"""Perceptron(numpy).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKi52sIGkD_wWzCVS1ToqwvdpkkZQX7R
"""

import numpy as np

class Perceptron:
    def __init__(self, input_size, learning_rate=0.1):
        self.weights = np.random.randn(input_size)
        self.bias = np.random.randn()
        self.lr = learning_rate

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def forward(self, X):
        self.z = np.dot(X, self.weights) + self.bias
        self.a = self.sigmoid(self.z)
        return self.a

    def backward(self, X, y):
        m = len(X)
        dz = self.a - y
        dw = np.dot(X.T, dz) / m
        db = np.sum(dz) / m
        self.weights -= self.lr * dw
        self.bias -= self.lr * db

    def train(self, X, y, epochs=1000):
        for i in range(epochs):
            self.forward(X)
            self.backward(X, y)

            if i % 100 == 0:
                loss = -np.mean(y * np.log(self.a + 1e-8) +
                                (1 - y) * np.log(1 - self.a + 1e-8))
                print(f"Epoch {i}, Loss: {loss:.4f}")

    def predict(self, X):
        probs = self.forward(X)
        return (probs > 0.5).astype(int)

# AND Gate dataset
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([0, 0, 0, 1])

# Create model
model = Perceptron(input_size=2, learning_rate=0.1)

# Train model
model.train(X, y, epochs=1000)

# Test
predictions = model.predict(X)
print("Predictions:", predictions)

